const express = require("express");
const bodyParser = require("body-parser");
const { jsPDF } = require("jspdf");
const fs = require("fs").promises;

const app = express();
const port = 3000;

app.use(bodyParser.urlencoded({ extended: false }));
app.use(express.static("public")); // Serve static files from the 'public' directory.

app.get("/", (req, res) => {
  res.sendFile(__dirname + "/form.html");
});

app.post("/generate", async (req, res) => {
  const { name, email, description } = req.body;

  // Create a new PDF document
  const doc = new jsPDF();

  // Add content to the PDF
  doc.text(20, 20, "PDF Form Example");

  // Add text to the top right corner
  doc.setFont("Times")
  const topRightText = "Generated by Your Name"; // Replace 'Your Name' with the actual name
  const topRightEmail = "Email: " + email; // Display the email
  const topRightX =
    doc.internal.pageSize.width -
    doc.getStringUnitWidth(topRightText) * doc.internal.getFontSize() -
    20;
  const topRightY = 10;

  doc.text(topRightX, topRightY, topRightText);
  doc.text(topRightX, topRightY + 10, topRightEmail);

  // Add centered text below
  const centeredText = "ТОВЧ ТАНИЛЦУУЛГА";
  const centeredX =
    doc.internal.pageSize.width / 2 -
    (doc.getStringUnitWidth(centeredText) * doc.internal.getFontSize()) / 2;
  const centeredY = 100;

  doc.text(centeredX, centeredY, centeredText);

  // Generate the PDF content
  const pdfBuffer = doc.output();

  // Set response headers for downloading the PDF
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', 'attachment; filename="form_data.pdf"');

  // Send the PDF content as the response
  res.send(pdfBuffer);
});




app.listen(port, () => {
  console.log(`Server is running on http://localhost:${port}`);
});
